baseURL = 'https://meowody.com/blog/'
locale = 'en-us'
title = 'meowody'
theme = "mana"

[params]
    # 主页标题下的描述文本
    description = "My blog about technology ... well, everything"
    favicon = "/favicon/favicon.ico"
    footerText = "[ Sincerity for sincerity, strength for a voice ] 京ICP备2026012168号  京公网安备11010802047850号"
    author = "baizeyv"

    heroTitleLine1 = "meowody blog"
    heroTitleLine2 = "TO EVERYTHING"

    [params.codeHighlight]
        darkTheme = "catppuccin-macchiato"   # Theme for dark mode
        lightTheme = "catppuccin-frappe"     # Theme for light mode

[params.copyright]
    startYear = 2026
    owner = "baizeyv"

[params.avatar]
    [params.avatar.home]
        assetPath = "images/testpic.png"
    [params.avatar.about]
        assetPath = "images/avatar.jpg"

[params.social]
    github = "https://github.com/baizeyv"
    gitlab = "https://gitlab.com/baizeyv"
    twitter = "_baizeyv"
    email = "baizeyv@gmail.com"

[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

[[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

[[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[[menus.main]]
    name = 'About'
    url = '/about/'
    weight = 40

[pagination]
    pageSize = 10

[markup]
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 6
        ordered = false

    [markup.goldmark]
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true
                title = true

    [markup.highlight]
        codeFences = true
        guessSyntax = true
        noClasses = false
        style = "catppuccin-macchiato"  # Default style

[params.admonitions]
    alertStyle = "emoji"

[outputs]
    home = ["HTML", "JSON"]