name: Deploy Hugo via Native SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build static files
        run: hugo --minify

      - name: Install sshpass and Deploy
        env:
          MY_USER: ${{ secrets.ECS_USER }}
          MY_HOST: ${{ secrets.ECS_HOST }}
          MY_PASS: ${{ secrets.ECS_PASS }}
        run: |
          # 安装 sshpass 辅助工具
          sudo apt-get update && sudo apt-get install -y sshpass
          
          echo "Host length: ${#MY_HOST}"
          echo "USER length: ${#MY_USER}"
          echo "PASS length: ${#MY_PASS}"
          
          # 执行 scp 命令
          # -o StrictHostKeyChecking=no：跳过首次连接确认指纹的步骤
          # -r：递归拷贝整个目录
          sshpass -p "$MY_PASS" scp -o StrictHostKeyChecking=no -r public/* "$MY_USER"@"$MY_HOST":/var/www/blog/